name: Deploying
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
      
      - name: Install Composer
        run: composer install
      
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: install packages
        run: npm i
      
      - name: Build assets
        run: npm run build
      
      - name: Prepare for deployment
        run:
          rm -rf node_modules
          rm -rf tests
          
      - name: Run post-deployment commands via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SERVER_DIR }}
            git pull
            php artisan migrate --force
            php artisan optimize
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
